import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from utils import utils_spectral as utils
from core.graph_generation import GraphGenerator

# -------------------------------
# Jupyter-safe output root
# -------------------------------
try:
    PACKAGE_ROOT = Path(__file__).resolve().parents[1]
except NameError:
    PACKAGE_ROOT = Path.cwd().resolve()

OUTPUT_ROOT = PACKAGE_ROOT / "outputs" / "laplacians"
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

class GraphLaplacianGenerator:

    def __init__(
        self,
        sim_metric="cosine",
        graph_method="knn",
        k=10,
        threshold=0.5,
        show_info=True,
        show_plots=True,
        save_dir: Path = OUTPUT_ROOT
    ):
        self.sim_metric = sim_metric
        self.graph_method = graph_method
        self.k = k
        self.threshold = threshold
        self.show_info = show_info
        self.show_plots = show_plots
        self.save_dir = Path(save_dir)
        self.save_dir.mkdir(parents=True, exist_ok=True)

    def generate_for_all_graphs(self, results: dict, name_prefix="laplacian_run"):
        """
        Runs Laplacian computation for all graphs generated by GraphGenerator.
        Expects `results` from GraphGenerator.run_grid_search().
        """
        all_outputs = {}

        for label, res in results.items():
            G = res['G']
            A = res['A']

            # Compute Laplacians
            D, L, L_sym, L_rw = utils.laplacians(A)

            # Info
            if self.show_info:
                self._summaries(D, L, L_sym, L_rw, label)

            # Plot spectra
            if self.show_plots:
                self._plot_spectra(L, L_sym, L_rw, label)

            # Save outputs
            self._save_outputs(A, D, L, L_sym, L_rw, f"{name_prefix}_{label}")

            all_outputs[label] = {'A': A, 'D': D, 'L': L, 'L_sym': L_sym, 'L_rw': L_rw}

        return all_outputs

    # ------------------------------------------
    # Helpers
    # ------------------------------------------
    def _summaries(self, D, L, L_sym, L_rw, label):
        print(f"\n[{label}] Shapes: D:{D.shape}, L:{L.shape}, L_sym:{L_sym.shape}, L_rw:{L_rw.shape}")
        vals, _ = np.linalg.eigh(L)
        print(f"[{label}] min eigen(L): {vals.min()}")

    def _plot_spectra(self, L, L_sym, L_rw, label):
        plt.figure(figsize=(12, 4))
        for i, (name, M) in enumerate([("L", L), ("L_sym", L_sym), ("L_rw", L_rw)], 1):
            plt.subplot(1, 3, i)
            w, _ = np.linalg.eigh(M)
            plt.plot(w, marker='o', linestyle='-', markersize=4)
            plt.title(f"{label} - {name} Spectrum")
            plt.xlabel("Index")
            plt.ylabel("Eigenvalue")
            plt.grid(True)
        plt.tight_layout()
        plt.show()

    def _save_outputs(self, A, D, L, L_sym, L_rw, name):
        out_dir = self.save_dir / name
        out_dir.mkdir(parents=True, exist_ok=True)

        np.save(out_dir / "adjacency.npy", A)
        np.save(out_dir / "degree.npy", D)
        np.save(out_dir / "L.npy", L)
        np.save(out_dir / "L_sym.npy", L_sym)
        np.save(out_dir / "L_rw.npy", L_rw)

        print(f"[INFO] Saved Laplacian outputs to {out_dir.resolve()}")


